config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'shares#index'
  resources :users, only: [:edit, :update, :show]
  resources :hosts
  resources :tags
  resources :shares, only: :index do
    collection do
      get 'search'
    end
  end
  resources :rooms do
    resources :room_images, only: [:create, :edit, :update, :show, :delete]
    resources :room_books, only: [:create, :edit, :update, :show, :delete]
  end
  resources :experiences do
    resources :experience_images, only: [:create, :edit, :update, :show, :delete]
    resources :experience_books, only: [:create, :edit, :update, :show, :delete]
  end
  resources :restaurants do
    resources :restaurant_images, only: [:create, :edit, :update, :show, :delete]
    resources :restaurant_books, only: [:create, :edit, :update, :show, :delete]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/host.rb
class Host < ApplicationRecord
  has_many :rooms
  has_many :restaurants
  has_many :experiences
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :host
  has_many :room_images
  has_many :room_books
  has_many :tags, through: :room_tags
  has_many :room_tags
end

app/models/room_book.rb
class RoomBook < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room_image.rb
class RoomImage < ApplicationRecord
  belongs_to :room
  mount_uploader :image, ImageUploader
end

app/models/room_tag.rb
class RoomTag < ApplicationRecord
  belongs_to :room
  belongs_to :tag
end

app/models/share.rb
class Share < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :rooms, through: :room_tags
  has_many :room_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :room_books
  has_many :experience_books
  has_many :restaurant_books
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_room_informationn_words

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :gender, :birth_month, :birth_day, :birth_year, :tel, :currency, :city_country, :discription])
  end

  def set_room_informationn_words
    @landmark = ['美ら海水族館', '首里城', '那覇市内', '石垣島', 'ひめゆりの塔','那覇国際空港']
    @amenity = ['Heating', 'Kitchen', 'TV', 'Wireless Internet', 'Air conditioning','Buzzer/wireless intercom', 'Doorman', 'Dryer', 'Family/kid friendly', 'Hair dryer', 'Hangers', 'Indoor fireplace', 'Iron', 'Laptop friendly workspace', 'Lock on bedroom door', 'Self Check-In', 'Shampoo', 'Washer']
    @rules = ['Pets allowed', 'Smoking allowed', 'Suitable for events', 'Check in is anytime after 3PM', 'Check out by 11AM']
    @meal_time_of_day = ['Breakfast', 'Lunch', 'Box Lunch option', 'Dinner']
  end
end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  layout 'host_page'
  before_action :authenticate_user!, only: :new

  def index
  end

  def new
    @host = Host.new
  end

  def create
    @host = Host.new(host_params)
    if @host.save
    else
      render new_group_path
    end
  end

  def show
    @rooms = Room.where(host_id: Host.where(user_id: current_user.id).ids)
  end

  def edit

  end

  def update
  end
  private
  def host_params
      params.require(:host).permit(:first_name, :last_name, :gender, :birth_month, :birth_day, :birth_year, :email, :tel, :native_language, :currency, :city_country, :description).merge(user_id: current_user.id)
  end
  def move_to_index
      redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/room_books_controller.rb
class RoomBooksController < ApplicationController
  def create
    @room_book = current_user.room_books.new(reservation_params)
    if @room_book.save
      redirect_to root_path notice:"予約が完了しました"
    else
      redirect_to root_path error:"予約が失敗しました"
    end
  end

  private
  def reservation_params
    params.require(:room_book).permit(:start_date, :end_date, :room_id, :total_guests, :requests).merge(user_id: current_user.id)
  end
end

app/controllers/room_images_controller.rb
class RoomImagesController < ApplicationController

  def create
    @roomimage = RoomImage.new(roomimage_params)
    if  @roomimage.save
      redirect_to edit_room_path(id: params[:room_id]), notice:"uploaded"
    else
      redirect_to edit_room_path(id: params[:room_id]), error:"fdiled"
    end
  end
  private
  def roomimage_params
      params.require(:room_image).permit(:title, :image, :room_id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  layout'host_page', only: [:new, :edit]
  # before_action :set_foom_pulldown_words, only: [:new, :create, :edit, :update]
  before_action :set_newroomdata_host, only: [:new, :create]
  before_action :set_currentroomdata_host, only: [:edit, :update]

  def index

  end

  def show
    @room = Room.find(params[:id])
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
    else
      render new_room_path
    end
  end

  def edit
    @roomimage = RoomImage.new
  end

  def update
    if @current_room_data.update(room_params)
      redirect_to root_path, notice: "部屋情報を変更しました：更新成功！"
    else
      render :edit
    end
  end

  private
  def room_params
    params.require(:room).permit(:title, :price, :cleaning_cost, :vat_jst, :location, :description, :hm_rooms, :hm_bets, :hm_bathrooms, :host_id, :roomtype, :country, :rate, amenity:[], facility:[], rules:[], meal_time_of_day:[], tag_ids: [])
  end

  # def set_foom_pulldown_words
  #   @landmark = ['美ら海水族館', '首里城', '那覇市内', '石垣島', 'ひめゆりの塔','那覇国際空港']
  #   @amenity = ['Heating', 'Kitchen', 'TV', 'Wireless Internet', 'Air conditioning','Buzzer/wireless intercom', 'Doorman', 'Dryer', 'Family/kid friendly', 'Hair dryer', 'Hangers', 'Indoor fireplace', 'Iron', 'Laptop friendly workspace', 'Lock on bedroom door', 'Self Check-In', 'Shampoo', 'Washer']
  #   @rules = ['Pets allowed', 'Smoking allowed', 'Suitable for events', 'Check in is anytime after 3PM', 'Check out by 11AM']
  #   @meal_time_of_day = ['Breakfast', 'Lunch', 'Box Lunch option', 'Dinner']
  # end

  def set_newroomdata_host
    @host = Host.where(user_id: current_user.id)
  end

  def set_currentroomdata_host
    @current_room_data = Room.find(params[:id])
    @host = Host.where(user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/shares_controller.rb
class SharesController < ApplicationController
  def index
    @rooms = Room.all
    @tags = Tag.all
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.where('keytag LIKE(?)', "%#{params[:keyword]}%").limit(20)
    respond_to do |format|
      format.html
      format.json
    end
  end
  def new
    @tag = Tag.new
  end
  def create
    @tag = Tag.new(tag_params)
    if @tag.save
    else
      render new_tag_path
    end
  end
  def edit
    @tag = Tag.new
  end
  def update
    @tag = Tag.new
  end
  private
  def tag_params
    params.require(:tag).permit(:keytag)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'user_page'
  def show
    user = User.find(params[:id])
  end

  def edit
  end

  def update
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/hosts/index.html.haml
.header_bottom2
  .header_bottom2_invitephoto
    .header_photo_above
      .page-container-responsive
        .floting_text
          .floting_text_field
            .floting_text_field_box
              .floting_text_field_box_inside
                .catchcopy
                  %h1.white.heavy.bold Earn money as an Airbnb host
                %p.white.space36 From saving for home repairs to taking a dream trip, hosts use extra income to fund their passions.
                .space36
                = link_to new_host_path, class:"btn btn-primary btn-large" do
                  Get start
.user_wrap.clearfix
  .user_content
    .host_block
      .floting_text
        .floting_text_field
          .catchcopy
            %h1.white.heavy.bold Get ready to meet your guests
          .space36
          = link_to new_host_path, class:"btn btn-primary btn-large" do
            Get start
        .hand-key

app/views/layouts/host_page.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", http: { equiv: "Content-Type"}}/
    %title Airbnb
    = favicon_link_tag('favicon.ico')
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %header.fix
    .header_top
      .leftbar
        .icon
          = link_to root_path do
            %svg{ class:"top_icon", viewBox:"0 0 1000 1000", role:"presentation", aria:{hidden:"true"}, focusable:"false", style:"display: block; fill: currentcolor; height: 1em; width: 1em;"}
              %path{ d:"M499.3 736.7c-51-64-81-120.1-91-168.1-10-39-6-70 11-93 18-27 45-40 80-40s62 13 80 40c17 23 21 54 11 93-11 49-41 105-91 168.1zm362.2 43c-7 47-39 86-83 105-85 37-169.1-22-241.1-102 119.1-149.1 141.1-265.1 90-340.2-30-43-73-64-128.1-64-111 0-172.1 94-148.1 203.1 14 59 51 126.1 110 201.1-37 41-72 70-103 88-24 13-47 21-69 23-101 15-180.1-83-144.1-184.1 5-13 15-37 32-74l1-2c55-120.1 122.1-256.1 199.1-407.2l2-5 22-42c17-31 24-45 51-62 13-8 29-12 47-12 36 0 64 21 76 38 6 9 13 21 22 36l21 41 3 6c77 151.1 144.1 287.1 199.1 407.2l1 1 20 46 12 29c9.2 23.1 11.2 46.1 8.2 70.1zm46-90.1c-7-22-19-48-34-79v-1c-71-151.1-137.1-287.1-200.1-409.2l-4-6c-45-92-77-147.1-170.1-147.1-92 0-131.1 64-171.1 147.1l-3 6c-63 122.1-129.1 258.1-200.1 409.2v2l-21 46c-8 19-12 29-13 32-51 140.1 54 263.1 181.1 263.1 1 0 5 0 10-1h14c66-8 134.1-50 203.1-125.1 69 75 137.1 117.1 203.1 125.1h14c5 1 9 1 10 1 127.1.1 232.1-123 181.1-263.1z"}
        .user_page_search_box
      .rightbar
        %ul
          %li.text_holizon
            .text_vertical
              .text_wrap
                = link_to hosts_path do
                  Become a Host
          %li.text_holizon
            .text_vertical
              .text_wrap
                = link_to '#' do
                  Trips
          %li.text_holizon
            .text_vertical
              .text_wrap
                = link_to '#' do
                  Messages
          %li.text_holizon
            .text_vertical
              .text_wrap
                = link_to '#' do
                  Help
          - if user_signed_in?
            %li.user
              .user_image#user_image
                = link_to '#' do
                  = image_tag("user_pic-50x50.png")
              .menu_list
                .user_menu{style:"display: none;"}
                  %ul
                    %li
                      .menu_text
                        .menu_text_content
                          = link_to edit_user_path(id: current_user.id) do
                            Edit profile
                      .menu_text
                        .menu_text_content
                          - if Host.where(user_id: current_user.id).ids[0].present?
                            = link_to host_path(Host.where(user_id: current_user.id).ids[0]) do
                              Host profile
                      .menu_text
                        .menu_text_content
                          = link_to destroy_user_session_path,{ method: :delete,} do
                            Log out
                %svg{ class:"hat", style:"display: none;"}
                  %path{ class:"white", d:"M0,10 20,10 10,0z"}
                  %path{ class:"gray_line", d:"M0,10 10,0 20,10"}
          - else
            %li.text_holizon
              .text_vertical
                .text_wrap
                  = link_to new_user_registration_path do
                    Sign up
            %li.text_holizon
              .text_vertical
                .text_wrap
                  = link_to new_user_session_path do
                    Log in
    .header_bottom
      .header_bottom_user_menu
        .header_bottom_user_menu_lists
          .header_bottom_user_menu_lists_list
            %ul
              %li
                .user_menu_list
                  .user_menu_list_text
                    = link_to new_room_path do
                      Register rooms
              %li
                .user_menu_list
                  .user_menu_list_text
                    = link_to new_restaurant_path do
                      Resister restaurants
              %li
                .user_menu_list
                  .user_menu_list_text
                    = link_to new_experience_path do
                      Resister experiences
  .header_position_space
  %body
    = yield
  .footer_wrap
    %footer
      .footer_contents
        .footer_contents_main
          .footer_contents_main_top.clearfix
            .select_cur_lang
              .select_cur_lang_each
                .select_cur_lang_each_box
                  = select :name, :name, [["English", "English"], ["Deutsch", "Deutsch"], ["中文（繁體字）", "中文（繁體字）"], ["日本語", "日本語"]], {}, {class: 'select_language'}
                %span{class:"arrowtobottom"}
                  %svg{ viewBox:"0 0 18 18", role:"presentation", aria:{hidden:"true"}, focusable:"false", style:"height: 16px; width: 16px; display: block; fill: rgb(72, 72, 72);"}
                    %path{ fill:{rule:"evenodd"}, d:"M16.291 4.295a1 1 0 1 1 1.414 1.415l-8 7.995a1 1 0 0 1-1.414 0l-8-7.995a1 1 0 1 1 1.414-1.415l7.293 7.29 7.293-7.29z"}
              .select_cur_lang_each
                .select_cur_lang_each_box
                  = select :name, :name, [["USD", "USD"], ["EUR", "EUR"], ["NTD", "NTD"], ["JPY", "JPY"]], {}, {class: 'select_language'}
                %span{class:"arrowtobottom"}
                  %svg{ viewBox:"0 0 18 18", role:"presentation", aria:{hidden:"true"}, focusable:"false", style:"height: 16px; width: 16px; display: block; fill: rgb(72, 72, 72);"}
                    %path{ fill:{rule:"evenodd"}, d:"M16.291 4.295a1 1 0 1 1 1.414 1.415l-8 7.995a1 1 0 0 1-1.414 0l-8-7.995a1 1 0 1 1 1.414-1.415l7.293 7.29 7.293-7.29z"}
            .link_lists
              .link_lists_main
                %h3.font About us
                %li
                  = link_to '#' do
                    About us
            .link_lists
              .link_lists_main
                %h3.font Discover
                %li
                  = link_to '#' do
                    Trust & Safety
            .link_lists
              .link_lists_main
                %h3.font Hosting
                %li
                  = link_to '#' do
                    Why Host
          .footer_contents_main_bottom
          .footer_border
          .footer_contents_main_bottom_contents
            .footer_contents_main_bottom_contents_left
              .mini_icon
                %svg{ viewBox:"0 0 1000 1000", role:"presentation", aria:{hidden:"true"}, focusable:"false", style:"height: 1.5em; width: 1.5em; display: block; fill: rgb(118, 118, 118);"}
                  %path{ d:"M499.3 736.7c-51-64-81-120.1-91-168.1-10-39-6-70 11-93 18-27 45-40 80-40s62 13 80 40c17 23 21 54 11 93-11 49-41 105-91 168.1zm362.2 43c-7 47-39 86-83 105-85 37-169.1-22-241.1-102 119.1-149.1 141.1-265.1 90-340.2-30-43-73-64-128.1-64-111 0-172.1 94-148.1 203.1 14 59 51 126.1 110 201.1-37 41-72 70-103 88-24 13-47 21-69 23-101 15-180.1-83-144.1-184.1 5-13 15-37 32-74l1-2c55-120.1 122.1-256.1 199.1-407.2l2-5 22-42c17-31 24-45 51-62 13-8 29-12 47-12 36 0 64 21 76 38 6 9 13 21 22 36l21 41 3 6c77 151.1 144.1 287.1 199.1 407.2l1 1 20 46 12 29c9.2 23.1 11.2 46.1 8.2 70.1zm46-90.1c-7-22-19-48-34-79v-1c-71-151.1-137.1-287.1-200.1-409.2l-4-6c-45-92-77-147.1-170.1-147.1-92 0-131.1 64-171.1 147.1l-3 6c-63 122.1-129.1 258.1-200.1 409.2v2l-21 46c-8 19-12 29-13 32-51 140.1 54 263.1 181.1 263.1 1 0 5 0 10-1h14c66-8 134.1-50 203.1-125.1 69 75 137.1 117.1 203.1 125.1h14c5 1 9 1 10 1 127.1.1 232.1-123 181.1-263.1z"}
              .company © Airbnb, Inc.
            .footer_contents_main_bottom_contents_right
              .footer_bottom_text
                %li.text
                  = link_to '#' do
                    Terms
                %li.text
                  = link_to '#' do
                    Privacy
                %li.text
                  = link_to '#' do
                    Site Map
                %li.sns
                  = link_to '#' do
                    %svg{ viewBox:"0 0 32 32", role:"img", aria:{label:"Facebook"}, focusable:"false", style:"height: 1em; width: 1em; display: block; fill: rgb(118, 118, 118);"}
                      %path{ fill:{rule:"evenodd"}, d:"M8 14.408v-4.165c0-.424.35-.812.77-.812h2.519V7.347c0-4.84 2.484-7.311 7.42-7.347 1.645 0 3.219.212 4.692.636.455.141.63.424.595.883l-.56 4.062c-.035.178-.14.354-.315.531-.21.105-.42.176-.63.14-.875-.247-1.784-.352-2.799-.352-1.399 0-1.61.283-1.61 1.73v1.8H22.6c.42 0 .805.423.805.883l-.349 4.17c0 .422-.35.705-.77.705H18.08v16c0 .424-.349.812-.769.812h-5.213c-.42 0-.804-.388-.804-.812V15.185h-2.52A.781.781 0 0 1 8 14.408"}
                %li.sns
                  = link_to '#' do
                    %svg{ viewBox:"0 0 32 32", role:"img", aria:{label:"Twitter"}, focusable:"false", style:"height: 1em; width: 1em; display: block; fill: rgb(118, 118, 118);"}
                      %path{ fill:{rule:"evenodd"}, d:"M31 6.359c-1.16.493-2.32.821-3.546.952 1.293-.755 2.22-1.872 2.718-3.384a13.048 13.048 0 0 1-3.913 1.512c-1.226-1.282-2.75-1.939-4.51-1.939-3.413 0-6.167 2.728-6.167 6.115 0 .493.067.953.166 1.38-4.94-.23-9.513-2.596-12.664-6.378-.563.954-.861 1.972-.861 3.089 0 2.07 1.027 3.914 2.75 5.063-.995-.032-1.922-.295-2.816-.755v.066c0 2.89 2.12 5.424 4.94 5.982-.63.165-1.16.231-1.624.231-.298 0-.696-.033-1.127-.132a6.074 6.074 0 0 0 5.737 4.242c-2.22 1.742-4.775 2.63-7.658 2.63-.563 0-1.06-.034-1.425-.1 2.85 1.841 6 2.76 9.413 2.76 7.294 0 12.83-4.012 15.514-9.302 1.359-2.661 2.021-5.359 2.021-8.086v-.46c-.033-.165-.033-.296-.033-.329A12.663 12.663 0 0 0 31 6.36"}
                %li.sns
                  = link_to '#' do
                    %svg{ viewBox:"0 0 24 24", role:"img", aria:{label:"Instagram"}, focusable:"false", style:"height: 1em; width: 1em; display: block; fill: rgb(118, 118, 118);"}
                      %path{ d:"M23.094.906C22.489.301 21.767 0 20.922 0H3.078C2.233 0 1.511.301.906.906.301 1.511 0 2.233 0 3.078v17.844c0 .845.301 1.567.906 2.172.605.605 1.327.906 2.172.906h17.844c.845 0 1.567-.301 2.172-.906.605-.605.906-1.327.906-2.172V3.078c0-.845-.301-1.567-.906-2.172zM8.618 8.65c.943-.911 2.077-1.367 3.4-1.367 1.331 0 2.47.456 3.413 1.367.943.91 1.413 2.013 1.413 3.303 0 1.291-.473 2.393-1.413 3.304-.943.911-2.082 1.367-3.414 1.367-1.322 0-2.456-.456-3.399-1.367-.943-.91-1.413-2.013-1.413-3.304 0-1.29.47-2.392 1.413-3.303zm12.664 11.632c0 .27-.093.498-.277.681a.923.923 0 0 1-.671.275H3.632a.927.927 0 0 1-.681-.275.921.921 0 0 1-.274-.68V10.155H4.88a6.737 6.737 0 0 0-.314 2.047c0 2.001.73 3.708 2.187 5.119 1.457 1.413 3.213 2.118 5.266 2.118a7.5 7.5 0 0 0 3.749-.97 7.288 7.288 0 0 0 2.718-2.632 6.93 6.93 0 0 0 1-3.632c0-.708-.106-1.391-.314-2.048h2.109v10.124zm0-13.954c0 .301-.106.559-.314.767a1.046 1.046 0 0 1-.766.313h-2.719c-.303 0-.558-.105-.766-.313a1.046 1.046 0 0 1-.314-.767V3.75c0-.291.106-.543.314-.756.208-.213.465-.321.766-.321h2.719c.303 0 .558.108.766.32.208.214.314.466.314.757v2.58z", fill:{rule:"evenodd"}}

app/views/rooms/create.html.haml
Thank you and welcome!

app/views/rooms/index.html.haml
.content.clearfix
  .main_content
    .left_content
      %h3.toppage Just booked in Tokyo
      .experiences
        .experience_box
          .experience
            .ex_image
            .subtitle
              .genre SAKE TASTING ·
              .currency ¥
              .price 8,000
            .introtitle Learn and Taste MANY Sake with an Expert
          .experience
            .ex_image
            .subtitle
              .genre SAKE TASTING ·
              .currency ¥
              .price 8,000
            .introtitle Learn and Taste MANY Sake with an Expert
          .experience
            .ex_image
            .subtitle
              .genre SAKE TASTING ·
              .currency ¥
              .price 8,000
            .introtitle Learn and Taste MANY Sake with an Expert
          .experience
            .ex_image
            .subtitle
              .genre SAKE TASTING ·
              .currency ¥
              .price 8,000
            .introtitle Learn and Taste MANY Sake with an Expert
      %h3.toppage Just booked in Taiwan
      .experiences
        .experience_box
          .experience
            .ex_image
            .subtitle
              .genre SAKE TASTING ·
              .currency ¥
              .price 8,000
            .introtitle Learn and Taste MANY Sake with an Expert
    .right_content
      .map_content
        #map
          :javascript
            function initMap() {
              var munchen = {lat: 48.137154, lng: 11.576124};
              var map = new google.maps.Map(document.getElementById('map'), {
                zoom: 4,
                center: munchen
              });
              var marker = new google.maps.Marker({
                position: munchen,
                map: map
              });
            }
          %script{async: :defer, src:"https://maps.googleapis.com/maps/api/js?key=AIzaSyA2C1ToN60wQB0sNEuL25b4tJQPm0C7nJc&callback=initMap"}

app/views/shares/index.html.haml
.content.clearfix
  .main_content
    - if @tags.present?
      - @tags.each do |landmark|
        %h3.toppage.clearfix
          Want to visit "#{landmark.keytag}"?
        .experiences
          .experience_box
            - @rooms.present?
            - @rooms.order('rate DESC').each do |room_tag|
              - if room_tag.tags.ids.include?(landmark.id)
                - if room_tag.present?
                  .experience
                    = link_to room_path(room_tag.id) do
                      .ex_image{style:"background-image: url(https://a0.muscache.com/airbnb/static/slash_host/never_a_stranger-91db63c401ad8301408ec3f24fd0f113.jpg); background-size:contain; background-repeat: no-repeat;"}
                      .subtitle
                        .genre #{room_tag.roomtype}
                        .currency _¥
                        .price #{number_with_delimiter(room_tag.price)}
                      .introtitle #{room_tag.title[0, 18]}...

app/views/tags/new.html.haml
.header_bottom2
  .header_bottom2_invitephoto
    .header_photo_above
      .page-container-responsive
        .floting_text
          .floting_text_field
            .floting_text_field_box
              .floting_text_field_box_inside
                .catchcopy
                  %h1.white.heavy.bold Resister Keywords here
                %p.white.space36
                .space36
.user_wrap.clearfix
  .user_content
    .user_content_right
      - if @tag.errors.any?
        .form__errors
          %h2= "#{@tag.errors.count}件のエラーが発生しました。"
          %ul
            - @tag.errors.full_messages.each do |msg|
              %li= msg
      .user_content_right_contents
        .user_content_right_contents_title Register key word
        .user_content_right_contents_content
          = form_for(@tag, type: :hidden) do |f|
            .user_content_right_contents_content_list
              .user_content_right_contents_content_list_title Keywored
              .user_content_right_contents_content_list_input
                = f.text_field :keytag, id:"", class:"user_inputbox", placeholder:"Set title! What do you want y to share?", autocomplete: "off"
                = f.submit :Send, class: "form__submit btn btn-primary btn-large"